### ISSUE TITLE
Many block drawings cause web map lags.... 

### ISSUE THREAD

**Issue by npdev453** [Dandielo/Dynmap-PreciousStones#7]

**Comment by RoboMWM** [comment]
What an amazing issue thread, glad I somehow happened to watch this repo

**Comment by Dandielo** [comment]
Well, sometimes it happens your hobbies shift and repos die ;P
Glad you noticed the potential

**Comment by RoboMWM** [comment]
don't even recall why  I watched this repo but I just saw the closed notification, then realized this issue is years old and was just closed by the author himself.
